SEGMENTS = ["pb2", "pb1", "pa", "np", "na", "mp", "ns", "ha"]


rule all:
    input:
        expand(
            #"max_freqs_log_likelyhood_plots/Max_Freq_Vs_LL_{segment}.png",
            "max_freqs_log_likelyhood/Max_Freq_Fasta_LL_{segment}.csv",
            segment=SEGMENTS,
        ),


rule translate_nucleotide_json:
    input:
        json_tree="h3n2_Sequences/h3n2_60y_{segment}.json",
        json_root="h3n2_Sequences/h3n2_60y_{segment}_root-sequence.json",
        script="scripts/translate_nucleotide_to_protein.py",
    output:
        "root_tree_translated/h3n2_60y_{segment}_root-sequence.json",
    conda:
        "envs/nextstrain_env.yaml"
    container:
        "envs/nextstrain-base.sif"
    shell:
        """
        mkdir -p root_tree_translated
        python {input.script} --tree {input.json_tree} --root {input.json_root} --segment {wildcards.segment}
        mv h3n2_60y_{wildcards.segment}_root-sequence.json root_tree_translated/h3n2_60y_{wildcards.segment}_root-sequence.json
        """


"""
rule download_nextstrain_data:
    output:
        "nextstrain_trees/flu_seasonal_h3n2_{segment}_60y.json",
        "nextstrain_trees/flu_seasonal_h3n2_{segment}_60y_tip-frequencies.json",
        "nextstrain_trees/flu_seasonal_h3n2_{segment}_60y_root-sequence.json",
    conda:
        "envs/nextstrain_env.yaml"
    container:
        "envs/nextstrain-base.sif"
    params:
        url="https://nextstrain.org/groups/blab/flu/seasonal/h3n2/{segment}/60y",
    shell:
        
        mkdir -p nextstrain_trees
        cd nextstrain_trees
        nextstrain remote download {params.url}
        
"""


rule extract_node_fastas:
    input:
        json_tree="h3n2_Sequences/h3n2_60y_{segment}.json",
        json_root="root_tree_translated/h3n2_60y_{segment}_root-sequence.json",
        script="scripts/extract_fasta_nodes.py",
    output:
        "node_fastas/nodeSeqs_{segment}.fasta",
    conda:
        "envs/nextstrain_env.yaml"
    container:
        "envs/nextstrain-base.sif"
    shell:
        """
        mkdir -p node_fastas
        python {input.script} --gene {wildcards.segment} --local-files True --tree {input.json_tree} --root {input.json_root} 
        mv nodeSeqs_{wildcards.segment}.fasta node_fastas/nodeSeqs_{wildcards.segment}.fasta
        """


rule extract_max_freq:
    input:
        json_tree="h3n2_Sequences/h3n2_60y_{segment}.json",
        node_fastas="node_fastas/nodeSeqs_{segment}.fasta",
        json_tip_freq="h3n2_Sequences/h3n2_60y_{segment}_tip-frequencies.json",
        script="scripts/extract_max_freq.py",
    output:
        "max_freqs/Max_Freq_Fasta_{segment}.csv",
    conda:
        "envs/nextstrain_env.yaml"
    container:
        "envs/nextstrain-base.sif"
    shell:
        """
        mkdir -p max_freqs
        python {input.script} --segment {wildcards.segment} --tree {input.json_tree} --tip-freq {input.json_tip_freq} --node-fasta {input.node_fastas}
        mv Max_Freq_Fasta_{wildcards.segment}.csv max_freqs/Max_Freq_Fasta_{wildcards.segment}.csv
        """


rule calc_ll_esm:
    input:
        max_freq="max_freqs/Max_Freq_Fasta_{segment}.csv",
        script="scripts/calc_ll_esm.py",
    output:
        "max_freqs_log_likelyhood/Max_Freq_Fasta_LL_{segment}.csv",
    # conda:
    #    "envs/nextstrain_env.yaml"
    shell:
        """
        mkdir -p max_freqs_log_likelyhood
        python {input.script} --max_freq {input.max_freq} --segment {wildcards.segment}
        mv Max_Freq_Fasta_LL_{wildcards.segment}.csv max_freqs_log_likelyhood/Max_Freq_Fasta_LL_{wildcards.segment}.csv
    """


rule generate_max_freq_v_ll_plots:
    input:
        max_freq_ll="max_freqs_log_likelyhood/Max_Freq_Fasta_LL_{segment}.csv",
        script="scripts/freq_v_ll_plots.py",
    output:
        "max_freqs_log_likelyhood_plots/Max_Freq_Vs_LL_{segment}.png",
    conda:
        "envs/data_analysis_env.yaml"
    shell:
        """
        mkdir -p max_freqs_vs_log_likelyhood_plots
        python {input.script} --Max_Freq_LL {input.max_freq_ll} --segment {wildcards.segment}
        mv Max_Freq_Vs_LL_{wildcards.segment}.png max_freqs_log_likelyhood_plots/Max_Freq_Vs_LL_{wildcards.segment}.png
        """
